language: node_js
dist: xenial
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script: cd aware-app
script:
  - ../scripts/aware-modules.sh --extract
  - npm test
  - CI=false npm run build
