version: '3'

services:
  database:
    container_name: database
    build:
      context: .
      dockerfile: database.Dockerfile
 
  server:
    container_name: server
    build: 
      context: .
      dockerfile: server.Dockerfile
    links:
      - database
    ports:
      - '5001:5001'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    depends_on:
      - database

  client:
    container_name: client
    build: 
      context: .
      dockerfile: client.Dockerfile
    links:
      - server  
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    depends_on:
      - server